# docker-compose.yml
version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"

  backend:
    build: ./backend
    container_name: node-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
